services:
  - type: web
    plan: free
    name: Benright-MD-V2
    runtime: docker
    region: Tanzania
    branch: V-2.00
    repo: https://github.com/Erickbenright/Benright-MD-V2
    #buildCommand: |
    #  apt-get update && \
    #  apt-get install -y ffmpeg && \
    #  npm install
    autoDeploy: true
    healthCheckPath: /
    #startCommand: npm start
    envVars:
      - key: SESSION_ID
        value: "YOUR_SESSION_ID"￼Enter
